type IU = "Iue";
type Upper = Uppercase<IU>;
// type Upper = "IUE" 대문자 변환
type Lower = Lowercase<IU>;
// type Lower = "iue" 소문자 변환
type Capital = Capitalize<IU>;
// type Capital = "Iue" 첫글자 대문자 변환 파스칼케이스
type UnCaptial = Uncapitalize<IU>;
// type UnCaptial = "iue" 첫글자 소문자 변환
